server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
      min: 8
      max: 200
  port: 8092
  servlet:
    context-path: /hospital-api

spring:
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://localhost:8765;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    database: 0
    host: localhost
    port: 6380
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  allow-concurrent-login: true
  is-share: false
  token-style: uuid
  isReadCookie: false


wechat:
  app-id: 123456
  app-secret: 123456
  pay:
    v3:
      patient-wx-api:
        app-id: 123456
        app-v3-secret: 123456
        mch-id: 123456
        domain: http://www.google.com/hospital-wx-api
        cert-path: apiclient_cert.p12

tencent:
  cloud:
    appId: 123456
    secretId: 123456
    secretKey: 123456
    face:
      groupName: hospital
      region: ap-beijing
  trtc:
    appId: 123456
    secretKey: 123456
    expire: 86400

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456

